name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: "index.html"
        target: "/var/www/html/"

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        script: |
          sudo systemctl restart nginx
